#!/bin/bash

usage=$(
cat <<EOF

$0 [OPTION]
	-l numeric level
		1 - stop after make
		2 - stop after make modules_install
		3 - complete to make install
	   Default is 3, complete to make install.

	-c sparse level
		1 - sparse only for newly compiled sources
		2 - sparse for all sources

	-j cpu cores (default is all cores)
	-b build versioning string
	-m make RHEL config file and copy to .config before build
	-v verbose make
	-k make kabitools database
	-e email address to notify on completion (default: tcamuso@redhat.com)
	-n disable email notification
	-h this help screen

	With no options, kmake will build and install the kernel
	and kernel modules using all processors.
EOF
)

# send_notification
# Send email notification when build completes
#
send_notification() {
	local status="$1"
	local elapsed="$2"
	local subject body

	[[ -z "$notify_email" ]] && return

	local kver
	kver=$(cat localversion 2>/dev/null || echo "unknown")
	local host
	host=$(hostname)

	if ((status == 0)); then
		subject="[kmake] Build SUCCESS on $host - $kver"
	else
		subject="[kmake] Build FAILED on $host - $kver (exit: $status)"
	fi

	body="Kernel build completed on $host
Version: $kver
Status: $(((status == 0)) && echo 'SUCCESS' || echo "FAILED (exit code: $status)")
Level: $level
Elapsed time: $elapsed
Working directory: $PWD

Log file: $(dirname "$PWD")/make.log"

	echo "$body" | mail -s "$subject" "$notify_email" 2>/dev/null || \
		echo "Warning: Could not send email notification to $notify_email"
}

mkconfig() {
	echo "Building the .config file."
	echo "This will overwrite your current .config file."
	read -r -n1 -p "press ctrl-C to quit, any other key to continue..."

	(( $(wc -l <<< $(grep dist-configs redhat/Makefile)) > 1 )) \
		&& make dist-configs || make rh-configs
	cp -vf redhat/configs/*-$(uname -i).config .config
}

# default settings
#
level=3		# set for complete build/install
sparse=0	# no sparse
verbose=""	# no verbose
kabi=""		# no kabitools database
cores=$(grep -cw processor /proc/cpuinfo)
notify_email="tcamuso@redhat.com"	# email notification

while getopts b:l:c:j:e:nvkhm OPTION; do
    case "$OPTION" in
	b ) echo "$OPTARG" > localversion
		;;
	l ) level=$OPTARG
		;;
	c ) sparse=$OPTARG
		;;
	j ) cores=$OPTARG
		;;
	v ) verbose="V=1"
		;;
	k ) kabi="K=1"
		;;
	m ) mkconfig
		;;
	e ) notify_email=$OPTARG
		;;
	n ) notify_email=""
		;;
	h ) echo -e "$usage"
            exit 0
		;;
	* ) echo -e "$usage"
	    exit 1
    esac
done

echo -n "building localversion: "
cat localversion
read -r -n1 -p "press ctrl-C to quit, any other key to continue..."

START1=$(date +%s)

# Assure that the option values cannot exceed the maximums
#
((sparse > 2)) && sparse=2
((level > 3)) && level=3

echo "make -j$cores $verbose C=$sparse 2>&1 | tee ../make.log" | tee ../make.log
make -j$cores $verbose $kabi C=$sparse $kabi 2>&1 | tee -a ../make.log
makestat=$?

END=$(date +%s)
DIFF=$(( END - START1 ))
minutes=$(( DIFF / 60 ))
seconds=$(( DIFF % 60 ))
echo | tee -a ../make.log
echo "Elapsed time: $minutes : $seconds" | tee -a ../make.log
echo | tee -a ../make.log

if ((level == 1)); then
	send_notification $makestat "$minutes : $seconds"
	exit $makestat
fi
if ((makestat != 0)); then
	send_notification $makestat "$minutes : $seconds"
	exit $makestat
fi

echo "make -j$cores $verbose C=$sparse modules_install 2>&1 | tee -a ../make.log" | \
	tee -a ../make.log
make -j$cores modules_install $verbose C=$sparse 2>&1 | tee -a ../make.log
makestat=$?

END=$(date +%s)
DIFF=$(( END - START1 ))
minutes=$(( DIFF / 60 ))
seconds=$(( DIFF % 60 ))
echo | tee -a ../make.log
echo "Elapsed time: $minutes : $seconds" | tee -a ../make.log
echo | tee -a ../make.log

if [ $level -eq 2 ]; then
	send_notification $makestat "$minutes : $seconds"
	exit $makestat
fi
if [ $makestat -ne 0 ]; then
	send_notification $makestat "$minutes : $seconds"
	exit $makestat
fi

echo "make -j$cores $verbose C=$sparse install 2>&1 | tee -a ../make.log" | \
	tee -a ../make.log
make -j$cores $verbose C=$sparse install 2>&1 | tee -a ../make.log
makestat=$?

END=$(date +%s)
DIFF=$(( END - START1 ))
minutes=$(( DIFF / 60 ))
seconds=$(( DIFF % 60 ))
echo | tee -a ../make.log
echo "Elapsed time: $minutes : $seconds" | tee -a ../make.log
echo | tee -a ../make.log

send_notification $makestat "$minutes : $seconds"
exit $makestat
